/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CntFlexyViewIslamVisitCreate {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitCreate[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitCreate100 {
        "pathToAssets": string;
        "payload": any;
    }
    interface CntFlexyViewIslamVisitFooter {
        "categories": any;
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitFooter[];
    }
    interface CntFlexyViewIslamVisitFooter100 {
        "categories": any;
    }
    interface CntFlexyViewIslamVisitHeader {
        "categories": any;
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitHeader[];
    }
    interface CntFlexyViewIslamVisitHeader100 {
        "categories": any;
        "pathToAssets": string;
    }
    interface CntFlexyViewIslamVisitInput {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitInput[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitInput100 {
        "payload": any;
    }
    interface CntFlexyViewIslamVisitTell {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitTell[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitTell100 {
        "pathToAssets": string;
        "payload": any;
    }
    interface CntFlexyViewIslamVisitWelcome {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitWelcome[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitWelcome100 {
        "pathToAssets": string;
        "payload": any;
    }
    interface CntFlexyViewIslamVisitWrapper {
        "forCarousel": any;
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitWrapper[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitWrapper100 {
        "pathToAssets": string;
        "payload": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewIslamVisitCreateElement extends Components.CntFlexyViewIslamVisitCreate, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitCreateElement: {
        prototype: HTMLCntFlexyViewIslamVisitCreateElement;
        new (): HTMLCntFlexyViewIslamVisitCreateElement;
    };
    interface HTMLCntFlexyViewIslamVisitCreate100Element extends Components.CntFlexyViewIslamVisitCreate100, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitCreate100Element: {
        prototype: HTMLCntFlexyViewIslamVisitCreate100Element;
        new (): HTMLCntFlexyViewIslamVisitCreate100Element;
    };
    interface HTMLCntFlexyViewIslamVisitFooterElement extends Components.CntFlexyViewIslamVisitFooter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitFooterElement: {
        prototype: HTMLCntFlexyViewIslamVisitFooterElement;
        new (): HTMLCntFlexyViewIslamVisitFooterElement;
    };
    interface HTMLCntFlexyViewIslamVisitFooter100Element extends Components.CntFlexyViewIslamVisitFooter100, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitFooter100Element: {
        prototype: HTMLCntFlexyViewIslamVisitFooter100Element;
        new (): HTMLCntFlexyViewIslamVisitFooter100Element;
    };
    interface HTMLCntFlexyViewIslamVisitHeaderElement extends Components.CntFlexyViewIslamVisitHeader, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitHeaderElement: {
        prototype: HTMLCntFlexyViewIslamVisitHeaderElement;
        new (): HTMLCntFlexyViewIslamVisitHeaderElement;
    };
    interface HTMLCntFlexyViewIslamVisitHeader100Element extends Components.CntFlexyViewIslamVisitHeader100, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitHeader100Element: {
        prototype: HTMLCntFlexyViewIslamVisitHeader100Element;
        new (): HTMLCntFlexyViewIslamVisitHeader100Element;
    };
    interface HTMLCntFlexyViewIslamVisitInputElement extends Components.CntFlexyViewIslamVisitInput, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitInputElement: {
        prototype: HTMLCntFlexyViewIslamVisitInputElement;
        new (): HTMLCntFlexyViewIslamVisitInputElement;
    };
    interface HTMLCntFlexyViewIslamVisitInput100Element extends Components.CntFlexyViewIslamVisitInput100, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitInput100Element: {
        prototype: HTMLCntFlexyViewIslamVisitInput100Element;
        new (): HTMLCntFlexyViewIslamVisitInput100Element;
    };
    interface HTMLCntFlexyViewIslamVisitTellElement extends Components.CntFlexyViewIslamVisitTell, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitTellElement: {
        prototype: HTMLCntFlexyViewIslamVisitTellElement;
        new (): HTMLCntFlexyViewIslamVisitTellElement;
    };
    interface HTMLCntFlexyViewIslamVisitTell100Element extends Components.CntFlexyViewIslamVisitTell100, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitTell100Element: {
        prototype: HTMLCntFlexyViewIslamVisitTell100Element;
        new (): HTMLCntFlexyViewIslamVisitTell100Element;
    };
    interface HTMLCntFlexyViewIslamVisitWelcomeElement extends Components.CntFlexyViewIslamVisitWelcome, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitWelcomeElement: {
        prototype: HTMLCntFlexyViewIslamVisitWelcomeElement;
        new (): HTMLCntFlexyViewIslamVisitWelcomeElement;
    };
    interface HTMLCntFlexyViewIslamVisitWelcome100Element extends Components.CntFlexyViewIslamVisitWelcome100, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitWelcome100Element: {
        prototype: HTMLCntFlexyViewIslamVisitWelcome100Element;
        new (): HTMLCntFlexyViewIslamVisitWelcome100Element;
    };
    interface HTMLCntFlexyViewIslamVisitWrapperElement extends Components.CntFlexyViewIslamVisitWrapper, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitWrapperElement: {
        prototype: HTMLCntFlexyViewIslamVisitWrapperElement;
        new (): HTMLCntFlexyViewIslamVisitWrapperElement;
    };
    interface HTMLCntFlexyViewIslamVisitWrapper100Element extends Components.CntFlexyViewIslamVisitWrapper100, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitWrapper100Element: {
        prototype: HTMLCntFlexyViewIslamVisitWrapper100Element;
        new (): HTMLCntFlexyViewIslamVisitWrapper100Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-islam-visit-create": HTMLCntFlexyViewIslamVisitCreateElement;
        "cnt-flexy-view-islam-visit-create-1-0-0": HTMLCntFlexyViewIslamVisitCreate100Element;
        "cnt-flexy-view-islam-visit-footer": HTMLCntFlexyViewIslamVisitFooterElement;
        "cnt-flexy-view-islam-visit-footer-1-0-0": HTMLCntFlexyViewIslamVisitFooter100Element;
        "cnt-flexy-view-islam-visit-header": HTMLCntFlexyViewIslamVisitHeaderElement;
        "cnt-flexy-view-islam-visit-header-1-0-0": HTMLCntFlexyViewIslamVisitHeader100Element;
        "cnt-flexy-view-islam-visit-input": HTMLCntFlexyViewIslamVisitInputElement;
        "cnt-flexy-view-islam-visit-input-1-0-0": HTMLCntFlexyViewIslamVisitInput100Element;
        "cnt-flexy-view-islam-visit-tell": HTMLCntFlexyViewIslamVisitTellElement;
        "cnt-flexy-view-islam-visit-tell-1-0-0": HTMLCntFlexyViewIslamVisitTell100Element;
        "cnt-flexy-view-islam-visit-welcome": HTMLCntFlexyViewIslamVisitWelcomeElement;
        "cnt-flexy-view-islam-visit-welcome-1-0-0": HTMLCntFlexyViewIslamVisitWelcome100Element;
        "cnt-flexy-view-islam-visit-wrapper": HTMLCntFlexyViewIslamVisitWrapperElement;
        "cnt-flexy-view-islam-visit-wrapper-1-0-0": HTMLCntFlexyViewIslamVisitWrapper100Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewIslamVisitCreate {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitCreate[];
        /**
          * Клик по картинке
         */
        "onClickCreateImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по позиционированной картинке
         */
        "onClickCreatePositionImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по второму subtext
         */
        "onClickCreateSecondSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по второму тексту
         */
        "onClickCreateSecondText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtext
         */
        "onClickCreateSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickCreateText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по третьему subtext
         */
        "onClickCreateThirdSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по третьему тексту
         */
        "onClickCreateThirdText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по title
         */
        "onClickCreateTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitCreate100 {
        "pathToAssets"?: string;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitFooter {
        "categories"?: any;
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitFooter[];
        /**
          * Клик по privacy
         */
        "onClickFooterPrivacy"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtext
         */
        "onClickFooterSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по support
         */
        "onClickFooterSupport"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по text
         */
        "onClickFooterText"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewIslamVisitFooter100 {
        "categories"?: any;
    }
    interface CntFlexyViewIslamVisitHeader {
        "categories"?: any;
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitHeader[];
        /**
          * Клик по картинке
         */
        "onClickHeaderImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по log in
         */
        "onClickHeaderLogIn"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по sign up
         */
        "onClickHeaderSignUp"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewIslamVisitHeader100 {
        "categories"?: any;
        "pathToAssets"?: string;
    }
    interface CntFlexyViewIslamVisitInput {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitInput[];
        /**
          * Клик по Input
         */
        "onClickInput"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по кнопке
         */
        "onClickInputButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickInputText"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitInput100 {
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitTell {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitTell[];
        /**
          * Клик по AppImage
         */
        "onClickTellAppImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по GoogleImage
         */
        "onClickTellGoogleImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtext
         */
        "onClickTellSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickTellText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по title
         */
        "onClickTellTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitTell100 {
        "pathToAssets"?: string;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitWelcome {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitWelcome[];
        /**
          * Клик по картинке
         */
        "onClickWelcomeImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по под тексту
         */
        "onClickWelcomeText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickWelcomeTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitWelcome100 {
        "pathToAssets"?: string;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitWrapper {
        "forCarousel"?: any;
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitWrapper[];
        /**
          * Клик по AppImage
         */
        "onClickWrapperAppImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по GoogleImage
         */
        "onClickWrapperGoogleImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по PhoneImage
         */
        "onClickWrapperPhoneImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по ProductImage
         */
        "onClickWrapperProductImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtext
         */
        "onClickWrapperSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtitle
         */
        "onClickWrapperSubTitle"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickWrapperText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по title
         */
        "onClickWrapperTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitWrapper100 {
        "pathToAssets"?: string;
        "payload"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-islam-visit-create": CntFlexyViewIslamVisitCreate;
        "cnt-flexy-view-islam-visit-create-1-0-0": CntFlexyViewIslamVisitCreate100;
        "cnt-flexy-view-islam-visit-footer": CntFlexyViewIslamVisitFooter;
        "cnt-flexy-view-islam-visit-footer-1-0-0": CntFlexyViewIslamVisitFooter100;
        "cnt-flexy-view-islam-visit-header": CntFlexyViewIslamVisitHeader;
        "cnt-flexy-view-islam-visit-header-1-0-0": CntFlexyViewIslamVisitHeader100;
        "cnt-flexy-view-islam-visit-input": CntFlexyViewIslamVisitInput;
        "cnt-flexy-view-islam-visit-input-1-0-0": CntFlexyViewIslamVisitInput100;
        "cnt-flexy-view-islam-visit-tell": CntFlexyViewIslamVisitTell;
        "cnt-flexy-view-islam-visit-tell-1-0-0": CntFlexyViewIslamVisitTell100;
        "cnt-flexy-view-islam-visit-welcome": CntFlexyViewIslamVisitWelcome;
        "cnt-flexy-view-islam-visit-welcome-1-0-0": CntFlexyViewIslamVisitWelcome100;
        "cnt-flexy-view-islam-visit-wrapper": CntFlexyViewIslamVisitWrapper;
        "cnt-flexy-view-islam-visit-wrapper-1-0-0": CntFlexyViewIslamVisitWrapper100;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-islam-visit-create": LocalJSX.CntFlexyViewIslamVisitCreate & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitCreateElement>;
            "cnt-flexy-view-islam-visit-create-1-0-0": LocalJSX.CntFlexyViewIslamVisitCreate100 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitCreate100Element>;
            "cnt-flexy-view-islam-visit-footer": LocalJSX.CntFlexyViewIslamVisitFooter & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitFooterElement>;
            "cnt-flexy-view-islam-visit-footer-1-0-0": LocalJSX.CntFlexyViewIslamVisitFooter100 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitFooter100Element>;
            "cnt-flexy-view-islam-visit-header": LocalJSX.CntFlexyViewIslamVisitHeader & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitHeaderElement>;
            "cnt-flexy-view-islam-visit-header-1-0-0": LocalJSX.CntFlexyViewIslamVisitHeader100 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitHeader100Element>;
            "cnt-flexy-view-islam-visit-input": LocalJSX.CntFlexyViewIslamVisitInput & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitInputElement>;
            "cnt-flexy-view-islam-visit-input-1-0-0": LocalJSX.CntFlexyViewIslamVisitInput100 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitInput100Element>;
            "cnt-flexy-view-islam-visit-tell": LocalJSX.CntFlexyViewIslamVisitTell & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitTellElement>;
            "cnt-flexy-view-islam-visit-tell-1-0-0": LocalJSX.CntFlexyViewIslamVisitTell100 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitTell100Element>;
            "cnt-flexy-view-islam-visit-welcome": LocalJSX.CntFlexyViewIslamVisitWelcome & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitWelcomeElement>;
            "cnt-flexy-view-islam-visit-welcome-1-0-0": LocalJSX.CntFlexyViewIslamVisitWelcome100 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitWelcome100Element>;
            "cnt-flexy-view-islam-visit-wrapper": LocalJSX.CntFlexyViewIslamVisitWrapper & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitWrapperElement>;
            "cnt-flexy-view-islam-visit-wrapper-1-0-0": LocalJSX.CntFlexyViewIslamVisitWrapper100 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitWrapper100Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
