/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CntFlexyViewIslamVisitCreate {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitCreate[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitCreate1_01 {
        "pathToAssets": string;
        "payload": any;
    }
    interface CntFlexyViewIslamVisitFooter {
        "categories": any;
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitFooter[];
    }
    interface CntFlexyViewIslamVisitFooter1_01 {
        "categories": any;
    }
    interface CntFlexyViewIslamVisitHeader {
        "categories": any;
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitHeader[];
    }
    interface CntFlexyViewIslamVisitHeader1_01 {
        "categories": any;
        "pathToAssets": string;
    }
    interface CntFlexyViewIslamVisitInput {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitInput[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitInput1_01 {
        "payload": any;
    }
    interface CntFlexyViewIslamVisitTell {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitTell[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitTell1_01 {
        "pathToAssets": string;
        "payload": any;
    }
    interface CntFlexyViewIslamVisitWelcome {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitWelcome[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitWelcome1_01 {
        "pathToAssets": string;
        "payload": any;
    }
    interface CntFlexyViewIslamVisitWrapper {
        "forCarousel": any;
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamVisitWrapper[];
        "payload": any;
    }
    interface CntFlexyViewIslamVisitWrapper1_01 {
        "pathToAssets": string;
        "payload": any;
    }
    interface CntFlexyViewIslamWindow {
        /**
          * Приём данных из массива для вывода
         */
        "intro": CntFlexyViewIslamWindow[];
        "payload": any;
    }
    interface CntFlexyViewIslamWindow1_01 {
        "payload": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewIslamVisitCreateElement extends Components.CntFlexyViewIslamVisitCreate, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitCreateElement: {
        prototype: HTMLCntFlexyViewIslamVisitCreateElement;
        new (): HTMLCntFlexyViewIslamVisitCreateElement;
    };
    interface HTMLCntFlexyViewIslamVisitCreate1_01Element extends Components.CntFlexyViewIslamVisitCreate1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitCreate1_01Element: {
        prototype: HTMLCntFlexyViewIslamVisitCreate1_01Element;
        new (): HTMLCntFlexyViewIslamVisitCreate1_01Element;
    };
    interface HTMLCntFlexyViewIslamVisitFooterElement extends Components.CntFlexyViewIslamVisitFooter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitFooterElement: {
        prototype: HTMLCntFlexyViewIslamVisitFooterElement;
        new (): HTMLCntFlexyViewIslamVisitFooterElement;
    };
    interface HTMLCntFlexyViewIslamVisitFooter1_01Element extends Components.CntFlexyViewIslamVisitFooter1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitFooter1_01Element: {
        prototype: HTMLCntFlexyViewIslamVisitFooter1_01Element;
        new (): HTMLCntFlexyViewIslamVisitFooter1_01Element;
    };
    interface HTMLCntFlexyViewIslamVisitHeaderElement extends Components.CntFlexyViewIslamVisitHeader, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitHeaderElement: {
        prototype: HTMLCntFlexyViewIslamVisitHeaderElement;
        new (): HTMLCntFlexyViewIslamVisitHeaderElement;
    };
    interface HTMLCntFlexyViewIslamVisitHeader1_01Element extends Components.CntFlexyViewIslamVisitHeader1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitHeader1_01Element: {
        prototype: HTMLCntFlexyViewIslamVisitHeader1_01Element;
        new (): HTMLCntFlexyViewIslamVisitHeader1_01Element;
    };
    interface HTMLCntFlexyViewIslamVisitInputElement extends Components.CntFlexyViewIslamVisitInput, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitInputElement: {
        prototype: HTMLCntFlexyViewIslamVisitInputElement;
        new (): HTMLCntFlexyViewIslamVisitInputElement;
    };
    interface HTMLCntFlexyViewIslamVisitInput1_01Element extends Components.CntFlexyViewIslamVisitInput1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitInput1_01Element: {
        prototype: HTMLCntFlexyViewIslamVisitInput1_01Element;
        new (): HTMLCntFlexyViewIslamVisitInput1_01Element;
    };
    interface HTMLCntFlexyViewIslamVisitTellElement extends Components.CntFlexyViewIslamVisitTell, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitTellElement: {
        prototype: HTMLCntFlexyViewIslamVisitTellElement;
        new (): HTMLCntFlexyViewIslamVisitTellElement;
    };
    interface HTMLCntFlexyViewIslamVisitTell1_01Element extends Components.CntFlexyViewIslamVisitTell1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitTell1_01Element: {
        prototype: HTMLCntFlexyViewIslamVisitTell1_01Element;
        new (): HTMLCntFlexyViewIslamVisitTell1_01Element;
    };
    interface HTMLCntFlexyViewIslamVisitWelcomeElement extends Components.CntFlexyViewIslamVisitWelcome, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitWelcomeElement: {
        prototype: HTMLCntFlexyViewIslamVisitWelcomeElement;
        new (): HTMLCntFlexyViewIslamVisitWelcomeElement;
    };
    interface HTMLCntFlexyViewIslamVisitWelcome1_01Element extends Components.CntFlexyViewIslamVisitWelcome1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitWelcome1_01Element: {
        prototype: HTMLCntFlexyViewIslamVisitWelcome1_01Element;
        new (): HTMLCntFlexyViewIslamVisitWelcome1_01Element;
    };
    interface HTMLCntFlexyViewIslamVisitWrapperElement extends Components.CntFlexyViewIslamVisitWrapper, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitWrapperElement: {
        prototype: HTMLCntFlexyViewIslamVisitWrapperElement;
        new (): HTMLCntFlexyViewIslamVisitWrapperElement;
    };
    interface HTMLCntFlexyViewIslamVisitWrapper1_01Element extends Components.CntFlexyViewIslamVisitWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamVisitWrapper1_01Element: {
        prototype: HTMLCntFlexyViewIslamVisitWrapper1_01Element;
        new (): HTMLCntFlexyViewIslamVisitWrapper1_01Element;
    };
    interface HTMLCntFlexyViewIslamWindowElement extends Components.CntFlexyViewIslamWindow, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamWindowElement: {
        prototype: HTMLCntFlexyViewIslamWindowElement;
        new (): HTMLCntFlexyViewIslamWindowElement;
    };
    interface HTMLCntFlexyViewIslamWindow1_01Element extends Components.CntFlexyViewIslamWindow1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewIslamWindow1_01Element: {
        prototype: HTMLCntFlexyViewIslamWindow1_01Element;
        new (): HTMLCntFlexyViewIslamWindow1_01Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-islam-visit-create": HTMLCntFlexyViewIslamVisitCreateElement;
        "cnt-flexy-view-islam-visit-create-1_01": HTMLCntFlexyViewIslamVisitCreate1_01Element;
        "cnt-flexy-view-islam-visit-footer": HTMLCntFlexyViewIslamVisitFooterElement;
        "cnt-flexy-view-islam-visit-footer-1_01": HTMLCntFlexyViewIslamVisitFooter1_01Element;
        "cnt-flexy-view-islam-visit-header": HTMLCntFlexyViewIslamVisitHeaderElement;
        "cnt-flexy-view-islam-visit-header-1_01": HTMLCntFlexyViewIslamVisitHeader1_01Element;
        "cnt-flexy-view-islam-visit-input": HTMLCntFlexyViewIslamVisitInputElement;
        "cnt-flexy-view-islam-visit-input-1_01": HTMLCntFlexyViewIslamVisitInput1_01Element;
        "cnt-flexy-view-islam-visit-tell": HTMLCntFlexyViewIslamVisitTellElement;
        "cnt-flexy-view-islam-visit-tell-1_01": HTMLCntFlexyViewIslamVisitTell1_01Element;
        "cnt-flexy-view-islam-visit-welcome": HTMLCntFlexyViewIslamVisitWelcomeElement;
        "cnt-flexy-view-islam-visit-welcome-1_01": HTMLCntFlexyViewIslamVisitWelcome1_01Element;
        "cnt-flexy-view-islam-visit-wrapper": HTMLCntFlexyViewIslamVisitWrapperElement;
        "cnt-flexy-view-islam-visit-wrapper-1_01": HTMLCntFlexyViewIslamVisitWrapper1_01Element;
        "cnt-flexy-view-islam-window": HTMLCntFlexyViewIslamWindowElement;
        "cnt-flexy-view-islam-window-1_01": HTMLCntFlexyViewIslamWindow1_01Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewIslamVisitCreate {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitCreate[];
        /**
          * Клик по картинке
         */
        "onClickCreateImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по позиционированной картинке
         */
        "onClickCreatePositionImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по второму subtext
         */
        "onClickCreateSecondSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по второму тексту
         */
        "onClickCreateSecondText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtext
         */
        "onClickCreateSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickCreateText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по третьему subtext
         */
        "onClickCreateThirdSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по третьему тексту
         */
        "onClickCreateThirdText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по title
         */
        "onClickCreateTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitCreate1_01 {
        "pathToAssets"?: string;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitFooter {
        "categories"?: any;
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitFooter[];
        /**
          * Клик по privacy
         */
        "onClickFooterPrivacy"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtext
         */
        "onClickFooterSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по support
         */
        "onClickFooterSupport"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по text
         */
        "onClickFooterText"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewIslamVisitFooter1_01 {
        "categories"?: any;
    }
    interface CntFlexyViewIslamVisitHeader {
        "categories"?: any;
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitHeader[];
        /**
          * Клик по картинке
         */
        "onClickHeaderImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по log in
         */
        "onClickHeaderLogIn"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по sign up
         */
        "onClickHeaderSignUp"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewIslamVisitHeader1_01 {
        "categories"?: any;
        "pathToAssets"?: string;
    }
    interface CntFlexyViewIslamVisitInput {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitInput[];
        /**
          * Клик по Input
         */
        "onClickInput"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по кнопке
         */
        "onClickInputButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickInputText"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitInput1_01 {
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitTell {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitTell[];
        /**
          * Клик по AppImage
         */
        "onClickTellAppImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по GoogleImage
         */
        "onClickTellGoogleImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtext
         */
        "onClickTellSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickTellText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по title
         */
        "onClickTellTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitTell1_01 {
        "pathToAssets"?: string;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitWelcome {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitWelcome[];
        /**
          * Клик по картинке
         */
        "onClickWelcomeImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по под тексту
         */
        "onClickWelcomeText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickWelcomeTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitWelcome1_01 {
        "pathToAssets"?: string;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitWrapper {
        "forCarousel"?: any;
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamVisitWrapper[];
        /**
          * Клик по AppImage
         */
        "onClickWrapperAppImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по GoogleImage
         */
        "onClickWrapperGoogleImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по PhoneImage
         */
        "onClickWrapperPhoneImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по ProductImage
         */
        "onClickWrapperProductImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtext
         */
        "onClickWrapperSubText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по subtitle
         */
        "onClickWrapperSubTitle"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по тексту
         */
        "onClickWrapperText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по title
         */
        "onClickWrapperTitle"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamVisitWrapper1_01 {
        "pathToAssets"?: string;
        "payload"?: any;
    }
    interface CntFlexyViewIslamWindow {
        /**
          * Приём данных из массива для вывода
         */
        "intro"?: CntFlexyViewIslamWindow[];
        /**
          * Клик по exit
         */
        "onClickWindowExit"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Facebook
         */
        "onClickWindowFacebook"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по FacebookText
         */
        "onClickWindowFacebookText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по heading
         */
        "onClickWindowHeading"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Input
         */
        "onClickWindowInput"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Instagram
         */
        "onClickWindowInstagram"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по InstagramText
         */
        "onClickWindowInstagramText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Link
         */
        "onClickWindowLink"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по LinkIcon
         */
        "onClickWindowLinkIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Messenger
         */
        "onClickWindowMessenger"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по MessengerText
         */
        "onClickWindowMessengerText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Reddit
         */
        "onClickWindowReddit"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по RedditText
         */
        "onClickWindowRedditText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Telegram
         */
        "onClickWindowTelegram"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по TelegramText
         */
        "onClickWindowTelegramText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Twitter
         */
        "onClickWindowTwitter"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по TwitterText
         */
        "onClickWindowTwitterText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по WeChat
         */
        "onClickWindowWeChat"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по WeChatText
         */
        "onClickWindowWeChatText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Whatsapp
         */
        "onClickWindowWhatsapp"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по WhatsappText
         */
        "onClickWindowWhatsappText"?: (event: CustomEvent<any>) => void;
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface CntFlexyViewIslamWindow1_01 {
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
        "payload"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-islam-visit-create": CntFlexyViewIslamVisitCreate;
        "cnt-flexy-view-islam-visit-create-1_01": CntFlexyViewIslamVisitCreate1_01;
        "cnt-flexy-view-islam-visit-footer": CntFlexyViewIslamVisitFooter;
        "cnt-flexy-view-islam-visit-footer-1_01": CntFlexyViewIslamVisitFooter1_01;
        "cnt-flexy-view-islam-visit-header": CntFlexyViewIslamVisitHeader;
        "cnt-flexy-view-islam-visit-header-1_01": CntFlexyViewIslamVisitHeader1_01;
        "cnt-flexy-view-islam-visit-input": CntFlexyViewIslamVisitInput;
        "cnt-flexy-view-islam-visit-input-1_01": CntFlexyViewIslamVisitInput1_01;
        "cnt-flexy-view-islam-visit-tell": CntFlexyViewIslamVisitTell;
        "cnt-flexy-view-islam-visit-tell-1_01": CntFlexyViewIslamVisitTell1_01;
        "cnt-flexy-view-islam-visit-welcome": CntFlexyViewIslamVisitWelcome;
        "cnt-flexy-view-islam-visit-welcome-1_01": CntFlexyViewIslamVisitWelcome1_01;
        "cnt-flexy-view-islam-visit-wrapper": CntFlexyViewIslamVisitWrapper;
        "cnt-flexy-view-islam-visit-wrapper-1_01": CntFlexyViewIslamVisitWrapper1_01;
        "cnt-flexy-view-islam-window": CntFlexyViewIslamWindow;
        "cnt-flexy-view-islam-window-1_01": CntFlexyViewIslamWindow1_01;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-islam-visit-create": LocalJSX.CntFlexyViewIslamVisitCreate & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitCreateElement>;
            "cnt-flexy-view-islam-visit-create-1_01": LocalJSX.CntFlexyViewIslamVisitCreate1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitCreate1_01Element>;
            "cnt-flexy-view-islam-visit-footer": LocalJSX.CntFlexyViewIslamVisitFooter & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitFooterElement>;
            "cnt-flexy-view-islam-visit-footer-1_01": LocalJSX.CntFlexyViewIslamVisitFooter1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitFooter1_01Element>;
            "cnt-flexy-view-islam-visit-header": LocalJSX.CntFlexyViewIslamVisitHeader & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitHeaderElement>;
            "cnt-flexy-view-islam-visit-header-1_01": LocalJSX.CntFlexyViewIslamVisitHeader1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitHeader1_01Element>;
            "cnt-flexy-view-islam-visit-input": LocalJSX.CntFlexyViewIslamVisitInput & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitInputElement>;
            "cnt-flexy-view-islam-visit-input-1_01": LocalJSX.CntFlexyViewIslamVisitInput1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitInput1_01Element>;
            "cnt-flexy-view-islam-visit-tell": LocalJSX.CntFlexyViewIslamVisitTell & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitTellElement>;
            "cnt-flexy-view-islam-visit-tell-1_01": LocalJSX.CntFlexyViewIslamVisitTell1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitTell1_01Element>;
            "cnt-flexy-view-islam-visit-welcome": LocalJSX.CntFlexyViewIslamVisitWelcome & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitWelcomeElement>;
            "cnt-flexy-view-islam-visit-welcome-1_01": LocalJSX.CntFlexyViewIslamVisitWelcome1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitWelcome1_01Element>;
            "cnt-flexy-view-islam-visit-wrapper": LocalJSX.CntFlexyViewIslamVisitWrapper & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitWrapperElement>;
            "cnt-flexy-view-islam-visit-wrapper-1_01": LocalJSX.CntFlexyViewIslamVisitWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamVisitWrapper1_01Element>;
            "cnt-flexy-view-islam-window": LocalJSX.CntFlexyViewIslamWindow & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamWindowElement>;
            "cnt-flexy-view-islam-window-1_01": LocalJSX.CntFlexyViewIslamWindow1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewIslamWindow1_01Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
